# Header
menu:
  归档: /archives
rss: /atom.xml
title: GARY.SHEN

author: GARY.SHEN
aboutme: Halo~

# Content
excerpt_link: 全文...
fancybox: true
date_format: 'YYYY年MM月DD日'

socials:
  github: ""
  flickr: ""
  email: ""
  wechat: ""



# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname:

# Miscellaneous
google_analytics: ''
gauges_analytics:
favicon: /images/avatar.png
avatar: "/images/avatar.png"
twitter:
google_plus:
fb_admins:
fb_app_id:
